[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
#Host = 'localhost'
Host = '172.21.0.1'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49988
Protocol = 'http'
StartupMsg = 'device random started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

# Pre-define Devices
[[DeviceList]]
  Name = 'virtual-device-random'
  Profile = 'Virtual Device'
  Description = 'virtual-device-random'
  Labels = [ 'virtual-device-random' ]
   [DeviceList.Protocols]
      [DeviceList.Protocols.other]
      Address = 'simple02'
      Port = '301'
